"use client";

import { Plus, Trash2 } from "lucide-react";
import type { RecipeDraft } from "@/lib/domain/recipe";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

type RecipeConfirmFormProps = { draft: RecipeDraft; imageUrls?: string[]; onChange: (draft: RecipeDraft) => void; coverUrl?: string | null; nameError?: string; stepsError?: string };

function withOrders(draft: RecipeDraft): RecipeDraft { return { ...draft, steps: draft.steps.map((step, index) => ({ ...step, order: index + 1 })) }; }

export function RecipeConfirmForm({ draft, imageUrls = [], onChange, coverUrl, nameError, stepsError }: RecipeConfirmFormProps) {
  const update = (next: RecipeDraft) => onChange(withOrders(next));
  const cover = coverUrl ?? imageUrls[0] ?? null;
  const editIngredient = (kind: "ingredients" | "seasonings", index: number, field: "name" | "amount", value: string) => update({ ...draft, [kind]: draft[kind].map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) });
  return <div data-testid="recipe-confirm-form" className="recipe-confirm-form grid gap-8">
    <section data-testid="recipe-confirm-summary" className="recipe-confirm-summary flex gap-5"><div data-testid="recipe-confirm-cover" className="recipe-confirm-cover">{cover ? <img src={cover} alt="菜谱封面" className="recipe-confirm-cover-image" /> : null}</div><div className="min-w-0 flex-1"><Label htmlFor="recipe-name">菜名</Label><Input id="recipe-name" aria-label="菜名" className="recipe-confirm-name mt-1" value={draft.name} onChange={(event) => update({ ...draft, name: event.target.value })} />{nameError ? <p role="alert" className="recipe-confirm-error">{nameError}</p> : null}<div className="recipe-confirm-metadata"><div><Label htmlFor="recipe-time">烹饪时间</Label><Input id="recipe-time" aria-label="烹饪时间" inputMode="numeric" value={draft.cookTimeMinutes?.toString() ?? ""} onChange={(event) => update({ ...draft, cookTimeMinutes: event.target.value ? Number(event.target.value) : null })} /></div><div><Label>难度</Label><Tabs value={draft.difficulty} onValueChange={(difficulty) => update({ ...draft, difficulty: difficulty as RecipeDraft["difficulty"] })}><TabsList aria-label="难度"><TabsTrigger value="easy">简单</TabsTrigger><TabsTrigger value="medium">中等</TabsTrigger><TabsTrigger value="hard">困难</TabsTrigger></TabsList></Tabs></div></div></div></section>
    <section className="recipe-confirm-section"><Label htmlFor="recipe-tags">标签</Label><div className="recipe-confirm-tags">{draft.tags.map((tag) => <span key={tag} className="recipe-confirm-tag">{tag}</span>)}</div><Input id="recipe-tags" aria-label="标签" className="mt-2" value={draft.tags.join(" ")} onChange={(event) => update({ ...draft, tags: event.target.value.split(/\s+/).filter(Boolean) })} /></section>
    <section data-testid="recipe-confirm-ingredients" className="recipe-confirm-section"><h2 className="recipe-confirm-section-title">食材与调料</h2>{(["ingredients", "seasonings"] as const).map((kind) => <div key={kind} className="recipe-confirm-ingredient-group">{draft[kind].map((item, index) => <div key={`${kind}-${index}`} className="recipe-confirm-ingredient-row grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] gap-2"><Input aria-label={kind === "ingredients" ? "食材名称" : "调料名称"} value={item.name} onChange={(event) => editIngredient(kind, index, "name", event.target.value)} /><Textarea aria-label={kind === "ingredients" ? "食材用量" : "调料用量"} rows={1} className="recipe-confirm-ingredient-amount resize-none" value={item.amount} onChange={(event) => editIngredient(kind, index, "amount", event.target.value)} /><Button variant="ghost" size="icon" aria-label={`删除${kind === "ingredients" ? "食材" : "调料"} ${index + 1}`} onClick={() => update({ ...draft, [kind]: draft[kind].filter((_, itemIndex) => itemIndex !== index) })}><Trash2 /></Button></div>)}<Button variant="ghost" onClick={() => update({ ...draft, [kind]: [...draft[kind], { name: "", amount: "", type: kind === "ingredients" ? "ingredient" : "seasoning" }] })}><Plus />添加{kind === "ingredients" ? "食材" : "调料"}</Button></div>)}</section>
    <section className="recipe-confirm-section"><h2 className="recipe-confirm-section-title">制作步骤</h2>{stepsError ? <p role="alert" className="recipe-confirm-error">{stepsError}</p> : null}<div data-testid="recipe-confirm-step-list" className="recipe-confirm-step-list">{draft.steps.map((step, index) => <div key={`${step.order}-${index}`} data-testid="step-row" className="recipe-confirm-step grid grid-cols-[auto_1fr_auto] gap-2"><span data-testid="step-order" className="recipe-confirm-step-order">{index + 1}</span><Textarea aria-label="步骤内容" className="recipe-confirm-step-text" value={step.text} onChange={(event) => update({ ...draft, steps: draft.steps.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item) })} /><Button variant="ghost" size="icon" aria-label={`删除步骤 ${index + 1}`} onClick={() => update({ ...draft, steps: draft.steps.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 /></Button></div>)}</div><Button variant="ghost" onClick={() => update({ ...draft, steps: [...draft.steps, { order: draft.steps.length + 1, text: "" }] })}><Plus />添加步骤</Button></section>
  </div>;
}
